### ISSUE TITLE
无监督句法分析的结构图

### ISSUE THREAD

**Issue by cpmss521** [bojone/perturbed_masking#1]
你好，我想问下，[无监督句法分析的图](https://camo.githubusercontent.com/5db8242b2cc9dcd8e32974d79770995a333b43fcc72171bf36847a16f35b02f1/68747470733a2f2f6b657875652e666d2f7573722f75706c6f6164732f323032302f30362f313038303131373532362e706e67) 是怎么画出来的？是根据json.dumps的可视化结果，手动绘画？还是？谢谢

**Comment by bojone** [comment]
手动画的，哈哈～
